/**
 * controllers/agentController.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Agent endpoints:
 *   • handlePanicScaffold — AI rescue checklist + boilerplate for at-risk tasks
 *   • handleOmniParse      — structured NL intent classifier for the Omni-Bar
 *   • handleOmniExecute    — actually runs the classified action and writes to
 *                            the activity log (called after countdown completes
 *                            or on high-confidence immediate execution)
 *
 * Removed: ETA/maps travel detection, inbox/email triage, Gmail send,
 * smart-route, and all Google OAuth. Velocity no longer touches maps or mail.
 */

const TaskModel    = require('../models/Task');
const { db }       = require('../utils/dataModel');
const { isConnected } = require('../db/connection');
const {
  generatePanicScaffold,
  parseOmniBarIntent,
} = require('../services/geminiService');
const { appendAgentLog, checkPolicyStatus } = require('./agentLogController');
const { handleTriage: runTriage } = require('./triageController');
const { handleNegotiate: runNegotiate } = require('./negotiateController');
const { handleReschedule: runReschedule } = require('./rescheduleController');

// ─── Panic Scaffold ───────────────────────────────────────────────────────────

async function handlePanicScaffold(req, res) {
  const { taskId } = req.body;
  const userId = req.userId;

  if (!taskId) return res.status(400).json({ error: 'taskId is required' });

  let task;
  if (isConnected()) {
    task = await TaskModel.findOne({ id: taskId, userId }).lean();
  } else {
    task = db.getTaskById(taskId);
  }
  if (!task) return res.status(404).json({ error: 'Task not found' });

  if (task.panicScaffold?.checklist?.length > 0) {
    return res.json({
      cached:      true,
      checklist:   task.panicScaffold.checklist,
      boilerplate: task.panicScaffold.boilerplate,
      repoUrl:     task.panicScaffold.repoUrl || null,
    });
  }

  try {
    const { checklist, boilerplate } = await generatePanicScaffold(task);

    let repoUrl = '';
    const githubToken = process.env.GITHUB_TOKEN;
    if (githubToken && githubToken !== 'your_github_token_here') {
      try {
        const { Octokit } = require('@octokit/rest');
        const octokit = new Octokit({ auth: githubToken });

        const slug = task.taskName
          .toLowerCase()
          .replace(/[^a-z0-9-]/g, '-')
          .replace(/-+/g, '-')
          .replace(/^-|-$/g, '')
          .slice(0, 60);
        const repoName = `velocity-${slug}-${Date.now().toString(36)}`;

        const { data: repo } = await octokit.repos.createForAuthenticatedUser({
          name:        repoName,
          description: `⚡ Zero-Hour scaffold: ${task.taskName}`,
          private:     false,
          auto_init:   false,
        });

        const readmeContent = Buffer.from(
          `# ⚡ ${task.taskName}\n\n> *Generated by Velocity Zero-Hour · ${new Date().toLocaleDateString()}*\n\n---\n\n## 🗺️ Roadmap\n\n${checklist.map(s => `- ${s}`).join('\n')}\n\n---\n\n## 🚀 Boilerplate\n\n\`\`\`\n${boilerplate}\n\`\`\`\n\n---\n\n*Autonomously scaffolded by Velocity Panic Mode.*\n`
        ).toString('base64');

        await octokit.repos.createOrUpdateFileContents({
          owner:   repo.owner.login,
          repo:    repoName,
          path:    'README.md',
          message: '⚡ Zero-Hour: autonomous scaffold commit',
          content: readmeContent,
        });

        repoUrl = repo.html_url;
        console.log(`[Agent] Created public GitHub repo: ${repoUrl}`);
      } catch (ghErr) {
        console.warn('[Agent] GitHub repo creation failed (non-fatal):', ghErr.message);
      }
    }

    const scaffoldData = { checklist, boilerplate, repoUrl, generatedAt: new Date().toISOString() };

    if (isConnected()) {
      await TaskModel.findOneAndUpdate(
        { id: taskId, userId },
        { $set: { panicScaffold: scaffoldData, hotStartContent: boilerplate } }
      );
    } else {
      db.updateTask(taskId, { hotStartContent: boilerplate });
    }

    // Write agent log entry — this is the most agentic action in the system
    const stepCount = checklist.length;
    await appendAgentLog(userId, {
      featureKey: 'panic',
      title: `Panic Mode activated for "${task.taskName}" — ${stepCount}-step rescue generated`,
      reasoning: `Deadline is imminent (< 24 hours). AI autonomously generated a ${stepCount}-step rescue checklist and runnable boilerplate${repoUrl ? ', then created a GitHub repo and committed the scaffold' : ''} — without any additional input.`,
      outcome: repoUrl
        ? `Rescue checklist + boilerplate generated. GitHub repo created: ${repoUrl}`
        : `Rescue checklist (${stepCount} steps) + boilerplate generated. Ready to execute immediately.`,
      autonomy: repoUrl ? 'autonomous' : 'assisted',
      undoable: false,
      relatedTaskId: taskId,
      relatedTaskName: task.taskName,
      metadata: { stepCount, hasRepo: !!repoUrl, repoUrl: repoUrl || null, taskType: task.taskType },
    }).catch(() => {});

    return res.json({ cached: false, checklist, boilerplate, repoUrl });
  } catch (err) {
    console.error('[Agent] Panic scaffold error:', err);
    return res.status(500).json({ error: 'Scaffold generation failed', message: err.message });
  }
}

// ─── OmniBar Intent Classifier ───────────────────────────────────────────────
// POST /api/agent/omni-parse
// Returns structured classification (intent, confidence, params, explanation, taskId)

async function handleOmniParse(req, res) {
  const { utterance } = req.body;
  const userId = req.userId;

  if (!utterance || typeof utterance !== 'string' || utterance.trim().length === 0) {
    return res.status(400).json({ error: 'utterance is required' });
  }

  let activeTasks;
  if (isConnected()) {
    activeTasks = await TaskModel.find({ userId, isRescheduled: { $ne: true } }).lean();
    activeTasks = activeTasks.filter(t => t.status !== 'COMPLETE' && t.status !== 'failed');
  } else {
    activeTasks = db.getAllTasks().filter(t => !t.isRescheduled && t.status !== 'COMPLETE' && t.status !== 'failed');
  }

  try {
    const result = await parseOmniBarIntent(utterance.trim(), activeTasks);

    // Phase 2 policy check: if classified intent has a learned policy against auto-acting,
    // downgrade confidence from 'high' to 'medium' so frontend shows suggestion instead of acting
    const policyFeatureMap = {
      run_triage:  'triage',
      panic_mode:  'panic',
      negotiate:   'negotiate',
      rebalance:   'rebalance',
    };
    const featureKey = policyFeatureMap[result.intent];
    if (featureKey && result.confidence === 'high') {
      // Check policy memory using the relevant metadata
      let metadata = {};
      if (result.intent === 'negotiate' && result.taskId) {
        const task = activeTasks.find(t => t.id === result.taskId);
        if (task) metadata = { recipient: task.recipientName || '' };
      }
      const policyCheck = await checkPolicyStatus(userId, featureKey, metadata);
      if (policyCheck.shouldSuggestOnly) {
        result.confidence = 'medium';
        result._policyDowngraded = true;
        result._policyLabel = policyCheck.policy?.policyLabel || featureKey;
        result.explanation = `(Policy: previously opted out of auto-${featureKey}) ${result.explanation}`;
      }
    }

    return res.json(result);
  } catch (err) {
    console.error('[Agent] OmniBar parse error:', err.message);
    return res.status(500).json({ error: 'Intent parsing failed', message: err.message });
  }
}

// ─── OmniBar Execute ──────────────────────────────────────────────────────────
// POST /api/agent/omni-execute
// Called by the frontend after countdown completes (or immediately on high confidence).
// Actually invokes the classified action and writes an Activity Log entry.
// Body: { intent, utterance, taskId, params, confidence }

async function handleOmniExecute(req, res) {
  const { intent, utterance, taskId, params = {}, confidence } = req.body;
  const userId = req.userId;

  if (!intent) return res.status(400).json({ error: 'intent is required' });

  let actionResult = null;
  let logEntry = null;

  try {
    switch (intent) {
      // ── create_task ────────────────────────────────────────────────────────
      case 'create_task': {
        const { v4: uuidv4 } = require('uuid');
        const taskName = params.taskName || utterance.slice(0, 80);
        const deadline = params.deadline || new Date(Date.now() + 7 * 86400000).toISOString();
        const category = (params.category || 'OTHER').toUpperCase();

        const newTask = {
          userId, id: uuidv4(),
          taskName,
          deadline,
          taskType: ['CODE', 'WRITING', 'DIAGRAM', 'OTHER'].includes(category) ? category : 'OTHER',
          cognitiveWeight: 'MEDIUM',
          selfOwned: true, recipientName: null,
          completionPercent: 0, status: 'GREEN',
          sparkline: [], subtasks: [], isRescheduled: false,
          hotStartContent: '', negotiatedDraft: '',
          driftExplanation: `Created via Omni-Bar: "${utterance}"`,
          energyLevel: 'Quick Wins', estimatedDuration: 60,
          creditValue: 100, creditsAwarded: false,
          createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
        };

        if (isConnected()) {
          const Task = require('../models/Task');
          await Task.create(newTask);
        } else {
          db.addTask ? db.addTask(newTask) : null;
        }

        actionResult = { created: true, task: newTask };
        logEntry = await appendAgentLog(userId, {
          featureKey: 'omnibar',
          title: `Omni-Bar created task: "${taskName}"`,
          reasoning: `You said: "${utterance}" → AI classified as create_task (${confidence} confidence). Task created directly without navigating to a form.`,
          outcome: `Task "${taskName}" added to your board. Deadline: ${new Date(deadline).toLocaleDateString()}.`,
          autonomy: confidence === 'high' ? 'countdown' : 'assisted',
          undoable: false,
          relatedTaskId: newTask.id,
          relatedTaskName: taskName,
          metadata: { utterance, intent, confidence, params, origin: 'omnibar' },
        });
        break;
      }

      // ── run_triage ─────────────────────────────────────────────────────────
      case 'run_triage': {
        // Delegate to the real triage controller
        await new Promise((resolve) => {
          const fakeReq = { userId, body: {} };
          const fakeRes = {
            status() { return this; },
            json(data) { actionResult = data; resolve(); return this; },
          };
          runTriage(fakeReq, fakeRes).catch(resolve);
        });

        // Log the omnibar origin on top of triage's own log entry
        logEntry = await appendAgentLog(userId, {
          featureKey: 'omnibar',
          title: `Omni-Bar triggered Triage — "${utterance}"`,
          reasoning: `You said: "${utterance}" → routed to Triage (${confidence} confidence). Triage ran immediately via Omni-Bar.`,
          outcome: actionResult?.triaged
            ? `Triage deferred "${actionResult.triagedTask?.taskName}" to free capacity.`
            : (actionResult?.reason || 'Triage ran — workload is manageable.'),
          autonomy: confidence === 'high' ? 'countdown' : 'assisted',
          undoable: false,
          relatedTaskId: actionResult?.triagedTask?.id || null,
          relatedTaskName: actionResult?.triagedTask?.taskName || null,
          metadata: { utterance, intent, confidence, origin: 'omnibar' },
        });
        break;
      }

      // ── panic_mode ─────────────────────────────────────────────────────────
      case 'panic_mode': {
        // Find the target task (from taskId or fallback to most critical)
        let task = null;
        if (taskId && isConnected()) {
          const Task = require('../models/Task');
          task = await Task.findOne({ id: taskId, userId }).lean();
        } else if (taskId) {
          task = db.getTaskById ? db.getTaskById(taskId) : null;
        }
        if (!task) {
          // Fallback: find most critical RED task
          const all = isConnected()
            ? await (require('../models/Task')).find({ userId }).lean()
            : (db.getAllTasks ? db.getAllTasks() : []);
          task = all.filter(t => t.status === 'RED' && !t.isRescheduled).sort((a, b) => new Date(a.deadline) - new Date(b.deadline))[0] || all[0];
        }

        if (!task) {
          actionResult = { error: 'No task found for panic mode' };
          break;
        }

        // Delegate to panic scaffold logic
        await new Promise((resolve) => {
          const fakeReq = { userId, body: { taskId: task.id } };
          const fakeRes = {
            status() { return this; },
            json(data) { actionResult = data; resolve(); return this; },
          };
          // Use the panic scaffold handler directly
          const TaskModelRef = require('../models/Task');
          generatePanicScaffold(task).then(async ({ checklist, boilerplate }) => {
            actionResult = { cached: false, checklist, boilerplate, taskName: task.taskName };
            if (isConnected()) {
              await TaskModelRef.findOneAndUpdate(
                { id: task.id, userId },
                { $set: { panicScaffold: { checklist, boilerplate, generatedAt: new Date().toISOString() }, hotStartContent: boilerplate } }
              );
            }
            resolve();
          }).catch(() => { actionResult = { error: 'scaffold failed' }; resolve(); });
        });

        logEntry = await appendAgentLog(userId, {
          featureKey: 'omnibar',
          title: `Omni-Bar activated Panic Mode for "${task.taskName}"`,
          reasoning: `You said: "${utterance}" → routed to Panic Mode (${confidence} confidence). Rescue scaffold generated immediately.`,
          outcome: actionResult?.checklist ? `${actionResult.checklist.length}-step rescue plan generated for "${task.taskName}".` : 'Panic Mode activated.',
          autonomy: confidence === 'high' ? 'countdown' : 'assisted',
          undoable: false,
          relatedTaskId: task.id,
          relatedTaskName: task.taskName,
          metadata: { utterance, intent, confidence, origin: 'omnibar', stepCount: actionResult?.checklist?.length || 0 },
        });
        break;
      }

      // ── smart_routing ──────────────────────────────────────────────────────
      case 'smart_routing': {
        // Find the top priority task and return it
        let allTasks = isConnected()
          ? await (require('../models/Task')).find({ userId }).lean()
          : (db.getAllTasks ? db.getAllTasks() : []);
        allTasks = allTasks.filter(t => !t.isRescheduled && t.status !== 'COMPLETE' && t.status !== 'failed');

        // Sort: RED first, then by hours/day required descending
        allTasks.sort((a, b) => {
          const statusOrder = { RED: 0, AMBER: 1, GREEN: 2 };
          const sa = statusOrder[a.status] ?? 3;
          const sb = statusOrder[b.status] ?? 3;
          if (sa !== sb) return sa - sb;
          return (b.currentPaceHoursPerDay || 0) - (a.currentPaceHoursPerDay || 0);
        });

        const topTask = allTasks[0] || null;
        actionResult = { topTask, totalActive: allTasks.length };

        logEntry = await appendAgentLog(userId, {
          featureKey: 'omnibar',
          title: `Omni-Bar: Smart Routing — "${topTask?.taskName || 'no tasks'}" is your top priority`,
          reasoning: `You said: "${utterance}" → routed to Smart Routing. AI ranked all ${allTasks.length} active tasks by urgency and pace to surface the most critical one.`,
          outcome: topTask ? `Top priority: "${topTask.taskName}" (${topTask.status}, ${topTask.currentPaceHoursPerDay}h/day required).` : 'No active tasks to route.',
          autonomy: 'assisted',
          undoable: false,
          relatedTaskId: topTask?.id || null,
          relatedTaskName: topTask?.taskName || null,
          metadata: { utterance, intent, confidence, origin: 'omnibar', totalTasks: allTasks.length },
        });
        break;
      }

      // ── negotiate ──────────────────────────────────────────────────────────
      case 'negotiate': {
        let task = null;
        if (taskId && isConnected()) {
          const Task = require('../models/Task');
          task = await Task.findOne({ id: taskId, userId }).lean();
        } else if (taskId) {
          task = db.getTaskById ? db.getTaskById(taskId) : null;
        }
        if (!task) {
          // Find best negotiate candidate: task with recipient, lowest completion
          let all = isConnected()
            ? await (require('../models/Task')).find({ userId }).lean()
            : (db.getAllTasks ? db.getAllTasks() : []);
          all = all.filter(t => !t.selfOwned && t.recipientName && !t.isRescheduled && t.status !== 'COMPLETE');
          all.sort((a, b) => (a.completionPercent || 0) - (b.completionPercent || 0));
          task = all[0] || null;
        }

        if (!task) {
          actionResult = { error: 'No negotiate-eligible task found (must have a recipient)' };
          break;
        }

        // Delegate to negotiate controller
        await new Promise((resolve) => {
          const fakeReq = { userId, body: { taskId: task.id } };
          const fakeRes = {
            status() { return this; },
            json(data) { actionResult = data; resolve(); return this; },
          };
          runNegotiate(fakeReq, fakeRes).catch(resolve);
        });

        logEntry = await appendAgentLog(userId, {
          featureKey: 'omnibar',
          title: `Omni-Bar drafted extension request for "${task.taskName}"`,
          reasoning: `You said: "${utterance}" → routed to Negotiate (${confidence} confidence). Draft prepared for ${task.recipientName}.`,
          outcome: `Extension request drafted for ${task.recipientName}. Review in the Negotiate modal before sending.`,
          autonomy: confidence === 'high' ? 'countdown' : 'assisted',
          undoable: false,
          relatedTaskId: task.id,
          relatedTaskName: task.taskName,
          metadata: { utterance, intent, confidence, origin: 'omnibar', recipient: task.recipientName },
        });
        break;
      }

      // ── rebalance ──────────────────────────────────────────────────────────
      case 'rebalance': {
        await new Promise((resolve) => {
          const fakeReq = { userId, body: {} };
          const fakeRes = {
            status() { return this; },
            json(data) { actionResult = data; resolve(); return this; },
          };
          runReschedule(fakeReq, fakeRes).catch(resolve);
        });

        logEntry = await appendAgentLog(userId, {
          featureKey: 'omnibar',
          title: `Omni-Bar rebalanced your schedule — "${utterance}"`,
          reasoning: `You said: "${utterance}" → routed to Rebalance (${confidence} confidence). AI repacked all subtasks into available work hours.`,
          outcome: actionResult?.message || 'Schedule rebalanced.',
          autonomy: confidence === 'high' ? 'countdown' : 'assisted',
          undoable: false,
          relatedTaskId: null,
          relatedTaskName: null,
          metadata: { utterance, intent, confidence, origin: 'omnibar', slotsRescheduled: actionResult?.rescheduled || 0 },
        });
        break;
      }

      // ── query / unclear fallback ───────────────────────────────────────────
      default: {
        actionResult = { info: true, message: 'No action taken — this was classified as a query or unclear intent.' };
        logEntry = await appendAgentLog(userId, {
          featureKey: 'omnibar',
          title: `Omni-Bar query: "${utterance.slice(0, 60)}"`,
          reasoning: `Classified as "${intent}" — no autonomous action appropriate. Returned information only.`,
          outcome: 'No action taken.',
          autonomy: 'assisted',
          undoable: false,
          relatedTaskId: null, relatedTaskName: null,
          metadata: { utterance, intent, confidence, origin: 'omnibar' },
        });
        break;
      }
    }

    return res.json({
      success: true,
      intent,
      result: actionResult,
      logEntryId: logEntry?.id || null,
    });

  } catch (err) {
    console.error('[Agent] OmniExecute error:', err.message);
    return res.status(500).json({ error: 'Action execution failed', message: err.message });
  }
}

module.exports = {
  handlePanicScaffold,
  handleOmniParse,
  handleOmniExecute,
};
