/**
 * controllers/hotstartController.js
 * POST /api/hotstart — scoped to req.userId
 */

const { generateHotStartScaffold } = require('../services/geminiService');
const { db } = require('../utils/dataModel');
const TaskModel = require('../models/Task');
const { isConnected } = require('../db/connection');

async function handleHotStart(req, res) {
  const { taskId } = req.body;
  const userId = req.userId;

  if (!taskId) return res.status(400).json({ error: 'Missing taskId' });

  let task;
  if (isConnected()) {
    task = await TaskModel.findOne({ id: taskId, userId }).lean();
  } else {
    task = db.getTaskById(taskId);
  }

  if (!task) return res.status(404).json({ error: 'Task not found' });

  if (task.hotStartContent && task.hotStartContent.trim().length > 0) {
    return res.json({ scaffold: task.hotStartContent });
  }

  try {
    const scaffold = await generateHotStartScaffold(task);

    if (isConnected()) {
      await TaskModel.findOneAndUpdate({ id: taskId, userId }, { $set: { hotStartContent: scaffold } });
    } else {
      db.updateTask(taskId, { hotStartContent: scaffold });
    }

    return res.json({ scaffold });
  } catch (err) {
    const fallback = generateFallbackScaffold(task);
    if (isConnected()) {
      await TaskModel.findOneAndUpdate({ id: taskId, userId }, { $set: { hotStartContent: fallback } });
    } else {
      db.updateTask(taskId, { hotStartContent: fallback });
    }
    return res.json({ scaffold: fallback, warning: 'Generated using fallback template (AI unavailable)' });
  }
}

function generateFallbackScaffold(task) {
  const type = (task.taskType || 'other').toLowerCase();
  if (type === 'code') {
    return `// HOT-START Scaffold — ${task.taskName}\n// Generated by Velocity · ${new Date().toLocaleDateString()}\n\n${(task.subtasks || []).map((s, i) => `// Step ${i + 1}: ${s.title} (~${s.estimatedMinutes} min)`).join('\n')}\n\nfunction main() {\n  console.log("Starting: ${task.taskName}");\n}\n\nmain();`;
  }
  if (type === 'diagram') {
    return `# HOT-START — ${task.taskName} Diagram Structure\n\n## Entities\n${(task.subtasks || []).map(s => `- [ ] ${s.title}`).join('\n') || '- [ ] Entity 1\n- [ ] Entity 2'}\n\n## Next Steps\n1. List all entities\n2. Define relationships\n3. Choose diagram tool (draw.io, Mermaid)`;
  }
  return `# HOT-START — ${task.taskName}\n\n## Overview\nTask: ${task.taskName}\nDeadline: ${new Date(task.deadline).toLocaleDateString()}\n\n${(task.subtasks || []).map((s, i) => `## Section ${i + 1}: ${s.title}\n- Estimated: ${s.estimatedMinutes} min\n- [ ] Key point 1\n- [ ] Key point 2`).join('\n\n')}\n\n## Checklist\n${(task.subtasks || []).map(s => `- [ ] ${s.title}`).join('\n') || '- [ ] Draft\n- [ ] Review\n- [ ] Submit'}`;
}

module.exports = { handleHotStart };
