export interface FeatureData {
  id: string;
  label: string;
  headline: string;
  description: string;
  layout: 'text-left' | 'text-right';
  mockupType: 'braindump' | 'chaos' | 'pace' | 'panic' | 'ultimatum' | 'negotiate';
}

export const FEATURES: FeatureData[] = [
  {
    id: 'braindump',
    label: 'Brain Dump',
    headline: 'Everything in your head. Structured in seconds.',
    description: 'Paste your entire mental backlog. Velocity extracts deadlines, estimates effort, and slots every item into your calendar — with urgency scores attached.',
    layout: 'text-left',
    mockupType: 'braindump',
  },
  {
    id: 'chaos-scanner',
    label: 'Chaos Scanner',
    headline: 'Scan your board. Find the landmines.',
    description: 'Point the scanner at a screenshot of any task board or email thread. Velocity reads it, extracts action items, and surfaces the ones about to blow up.',
    layout: 'text-right',
    mockupType: 'chaos',
  },
  {
    id: 'pace-tracking',
    label: 'Live Pace Tracking',
    headline: 'Know your pace before it\'s too late.',
    description: 'Every task has a required daily pace to hit its deadline. Velocity watches your check-ins and adjusts the pace bar in real time — green means go, red means intervention.',
    layout: 'text-left',
    mockupType: 'pace',
  },
  {
    id: 'panic-mode',
    label: 'Panic Mode',
    headline: 'One hour left. Velocity builds the scaffold.',
    description: 'Hit Panic Mode on any task and get an instant checklist, boilerplate code, and a repo starter — generated by AI in under 10 seconds.',
    layout: 'text-right',
    mockupType: 'panic',
  },
  {
    id: 'ultimatum',
    label: 'The Ultimatum',
    headline: 'Two tasks. One slot. You decide.',
    description: 'When two deadlines genuinely conflict, Velocity stops auto-rescheduling and forces a conscious choice. The losing task is logged — not silently dropped.',
    layout: 'text-left',
    mockupType: 'ultimatum',
  },
  {
    id: 'negotiate',
    label: 'Negotiate',
    headline: 'Can\'t make a deadline? Send the email automatically.',
    description: 'Velocity drafts a professional extension request tailored to the task, the recipient, and the context — ready to send in one click.',
    layout: 'text-right',
    mockupType: 'negotiate',
  },
];
